### ISSUE TITLE
error keys

### ISSUE THREAD

**Issue by chronoss09** [AcK77/XCIRepacker#1]
![Capture](https://user-images.githubusercontent.com/17669980/64461751-518d5c00-d0fe-11e9-849c-24848582c1ea.PNG)

**Comment by AcK77** [comment]
You need to have switch keys somewhere. I will edit the Readme to add this forgotten information.

https://github.com/Thealexbarney/LibHac/blob/master/KEYS.md

You can put the keys file near the executable too.

--- Edit

Fixed in e4d3beed6bad33530edda6b91e644421f78eb66c
