### ISSUE TITLE
Fix output path

### ISSUE THREAD

**Issue by SpikeSP87** [AcK77/XCIRepacker#2]
Hi, i've been using your tool, and there is a little bug. I'll try to explain it with an example:

If we are supposing that we are working from the path: 'd:\temp\xci_repacker'
When you launch a conversion, for example 'test.xci'; and this file is at the same path as the tool (to simplify this example); the tool forgets to add a '\\' character at the end of the output path:
· Actual output: d:\temp\xci_repackertest.nsp
· Expected output: d:\temp\xci_repacker\test.nsp

Good job on the tool, it's very easy to use.

**Comment by AcK77** [comment]
Nice catch, I will fix that when I'll update patches for 9.0.0!
Thanks.

**Comment by AcK77** [comment]
Fixed in #8
